version: '3.'
services:
  airdrop_nginx:
    image: nginx:1.17-alpine
    container_name: airdrop_app_nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - airdrop_app_network
      
  airdrop_app:
    build:
      args:
        user: nginx
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: airdrop_app_image
    container_name: airdrop_app_container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - airdrop_app_network
  airdrop_npm:  
    image: node:21.4.0-alpine
    container_name: airdrop_npm
    working_dir: /var/www/
    command: "npm run prod"
    entrypoint: ['npm', '--no-bin-links']
    volumes: 
      - "./:/var/www"  
    depends_on:
      - airdrop_app
    networks:
      - airdrop_app_network
networks:
  airdrop_app_network:
    driver: bridge
